/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyListIndexRouteImport } from './routes/my-list/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBookIdIndexRouteImport } from './routes/books/$bookId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListIndexRoute = MyListIndexRouteImport.update({
  id: '/my-list/',
  path: '/my-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/books/$bookId/',
  path: '/books/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksIndexRoute
  '/my-list': typeof MyListIndexRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksIndexRoute
  '/my-list': typeof MyListIndexRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books/': typeof BooksIndexRoute
  '/my-list/': typeof MyListIndexRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books' | '/my-list' | '/books/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books' | '/my-list' | '/books/$bookId'
  id: '__root__' | '/' | '/books/' | '/my-list/' | '/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  MyListIndexRoute: typeof MyListIndexRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list/': {
      id: '/my-list/'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  MyListIndexRoute: MyListIndexRoute,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
